### ISSUE TITLE
HW 1, Question 3

### ISSUE THREAD

**Issue by Audace** [kapelner/Wharton_Stat_422_722#1]
I'm confused how question three can be calculated without any data. Is there a missing dataset, or are we supposed to pull from an online source?

**Comment by Audace** [comment]
Going to go with Catherine Ross's dataset from 1990. Has all of the data mentioned: [dataset](http://www.icpsr.umich.edu/icpsrweb/ICPSR/studies/6666). See [here](https://github.com/IamGianluca/arm/blob/89c43c8c9f630908f2a21e2b7d09fdf588e2dc5b/ch4/arm_ch4p2.md) for easily cleaning the data.

**Comment by kapelner** [comment]
There in no dataset; you must imagine one. You are supposed to make up
reasonable output.
